import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = {
  title: "Privacy Policy | Andellian",
  description:
    "Learn how Andellian.com and Andellian Press handle mailing-list subscriptions, messages, and website information.",
};

export default function PrivacyPage() {
  return (
    <>
      <a className="skip-link" href="#main-content">
        Skip to content
      </a>

      <SiteHeader />

      <main className="legal-page" id="main-content">
        <div className="site-shell reading-column">
          <h1>Privacy Policy</h1>
          <p className="legal-meta">
            <strong>Effective date:</strong> July 24, 2026
            <br />
            <strong>Last updated:</strong> July 24, 2026
          </p>

          <p>
            Andellian.com is operated by Alexander Dean and Andellian Press.
            This Privacy Policy explains what information may be collected when
            you use the site, how that information is used, and the choices
            available to you.
          </p>

          <h2>Information we collect</h2>

          <h3>Mailing-list subscriptions</h3>
          <p>
            When you subscribe to Andellian Readers, we collect the email
            address you provide and information associated with the
            subscription, such as confirmation status, signup date, and
            newsletter engagement data generated by the email service.
          </p>
          <p>
            The site uses double opt-in. Your subscription becomes active only
            after you confirm it through the email sent to the address you
            provided.
          </p>

          <h3>Messages you send</h3>
          <p>
            When you contact us by email, we receive your email address and the
            contents of your message.
          </p>

          <h3>Technical information</h3>
          <p>
            Our hosting and email-service providers may process limited
            technical information needed to deliver, secure, and operate the
            site and mailing list. This may include an IP address, browser or
            device information, timestamps, and cookies or similar technologies
            used by those providers.
          </p>

          <h2>How we use information</h2>
          <p>We use information collected through Andellian.com to:</p>
          <ul>
            <li>deliver requested stories and mailing-list emails;</li>
            <li>
              share news, excerpts, lore, maps, publication information, and
              behind-the-scenes material from Andellian;
            </li>
            <li>maintain and protect the site and mailing list;</li>
            <li>respond to messages and requests;</li>
            <li>understand general newsletter performance; and</li>
            <li>comply with applicable legal obligations.</li>
          </ul>
          <p>We do not sell or rent subscriber information.</p>

          <h2>MailerLite</h2>
          <p>
            We use MailerLite to manage the Andellian Readers mailing list,
            collect subscriptions, deliver automated emails, and send
            newsletters. MailerLite may process subscriber information using
            cookies, tracking pixels, unique identifiers, and similar
            technologies in order to provide and improve its services.
          </p>
          <p>
            MailerLite’s privacy policy is available at:{" "}
            <a
              href="https://www.mailerlite.com/legal/privacy-policy"
              rel="noopener noreferrer"
              target="_blank"
            >
              https://www.mailerlite.com/legal/privacy-policy
            </a>
          </p>
          <p>
            You may unsubscribe at any time by using the unsubscribe link
            included in each mailing-list email.
          </p>

          <h2>Cookies and analytics</h2>
          <p>
            At launch, Andellian.com does not use advertising cookies or a
            separate advertising or analytics platform. MailerLite and the
            site’s hosting provider may use technical cookies or similar
            technologies that are necessary for their services, security, and
            performance.
          </p>
          <p>
            If additional analytics, advertising, or cookie-based services are
            added later, this policy will be updated and any legally required
            notice or consent controls will be added before those services are
            enabled.
          </p>

          <h2>How information is shared</h2>
          <p>
            Information may be shared only as reasonably necessary with service
            providers that help operate Andellian.com and the mailing list,
            including MailerLite and the site’s hosting or infrastructure
            providers. Information may also be disclosed when required by law
            or when reasonably necessary to protect the rights, security, or
            safety of Andellian Press, site visitors, or others.
          </p>

          <h2>Data retention</h2>
          <p>
            Subscriber information is retained while you remain subscribed and as
            reasonably necessary afterward to honor unsubscribe requests,
            maintain suppression records, resolve disputes, and comply with
            legal obligations. Email correspondence may be retained for as long
            as reasonably necessary to respond and maintain appropriate business
            records.
          </p>

          <h2>Your choices</h2>
          <p>You may:</p>
          <ul>
            <li>
              unsubscribe through the link included in any mailing-list email;
            </li>
            <li>
              request access to or correction of information you have provided;
            </li>
            <li>
              request deletion of information, subject to information that must
              be retained for legal, security, or unsubscribe-record purposes;
              or
            </li>
            <li>ask a privacy-related question by contacting us.</li>
          </ul>

          <h2>Children’s privacy</h2>
          <p>
            Andellian.com is not directed to children under 13, and we do not
            knowingly collect personal information from children under 13.
          </p>

          <h2>International processing</h2>
          <p>
            Service providers may process information in countries other than the
            country where you live. Those providers are responsible for
            applying the safeguards required by the laws that govern their
            services.
          </p>

          <h2>Changes to this policy</h2>
          <p>
            This policy may be updated as Andellian.com, its mailing list, or
            its service providers change. The effective date shown above will be
            revised when material changes are made.
          </p>

          <h2>Contact</h2>
          <p>For privacy questions or requests, contact:</p>
          <p>
            <strong>Alexander Dean / Andellian Press</strong>
            <br />
            <a href="mailto:contact@andellian.com">contact@andellian.com</a>
          </p>

          <p className="legal-back">
            <Link href="/">Return to Andellian</Link>
          </p>
        </div>
      </main>

      <SiteFooter />
    </>
  );
}
